### ISSUE TITLE
Runtime exception when using "go get github.com/z7zmey/php-parser"

### ISSUE THREAD

**Issue by prasad83** [z7zmey/php-parser#119]
I'm on (go version go1.14 linux/amd64)

```
go get github.com/z7zmey/php-parser
```

Shows

```
# github.com/z7zmey/php-parser
runtime.main_main·f: function main is undeclared in the main package
```

**Comment by prasad83** [comment]
Likely issue on master (0.8 version)

**Comment by z7zmey** [comment]
Hi @prasad83. I have updated the project layout.
You can use `go get github.com/z7zmey/php-parser/cmd/php-parser`  to get the CLI tool.

Readme was updated at #124
