### ISSUE TITLE
Update Example in README

### ISSUE THREAD

**Issue by silbinarywolf** [z7zmey/php-parser#12]
**What actually works**

- There doesn't seem to be a nice way to get error messages, or at least it's not obvious to me. I'd assume perhaps I need to walk the AST and find nodes marked with errors or something?

```
rootNode, comments, positions := php7.Parse(bytes.NewBufferString(`<? echo "Hello world";`), "example.php")
//How do we get a list of errors easily?
//How do we get the position/column?
//for _, e := range parser.GetErrors() {
//	fmt.Println(e)
//}
visitor := visitor.Dumper{
	Writer:    os.Stdout,
	Indent:    "",
	Comments:  comments,
	Positions: positions,
}
rootNode.Walk(visitor)
```

**The non-working example given**
```
src := bytes.NewBufferString(`<? echo "Hello world";`)

parser := php7.NewParser(src, "example.php")
parser.Parse()

for _, e := range parser.GetErrors() {
	fmt.Println(e)
}

visitor := visitor.Dumper{
	Writer:    os.Stdout,
	Indent:    "",
	Comments:  parser.GetComments(),
	Positions: parser.GetPositions(),
}

rootNode := parser.GetRootNode()
rootNode.Walk(visitor)
```

**Comment by z7zmey** [comment]
I limited by `goyacc`, and I can only save unexpected tokens as errors. When this happens the parser skips the token and try to recover parsing process, so the error is not a part of AST.
AST contains only nodes that can be correctly parsed.

> The non-working example given

Are you at the `master` branch?
Run `go get -u github.com/z7zmey/php-parser`
