### ISSUE TITLE
printer: Does not keep formatting as-is

### ISSUE THREAD

**Issue by silbinarywolf** [z7zmey/php-parser#13]
**What I expected**
When using the package simply labelled `printer*, I assumed it would just print the file with all the formatting it had previously, however it seems this is just meant to be a pretty printer.

What's the plan for retaining formatting, if any? My use case is that I'd like to make something that'll resolve all my PHP namespaces in Sublime Text when you hit save.

For saving the data back out, I'm sure I could do a sort of hack where I only modify the lines affected, but I'm hoping retention of formatting is do-able and not too difficult so I can avoid that effort

At the very least, can the `Printer` struct perhaps just be renamed to `PrettyPrinter`?

**Comment by z7zmey** [comment]
Pretty Printer must cover both use cases:
- code generation
- changing parsed AST

roadmap:
- [x] simple PrettyPrinter that prints only AST
- [ ] save all Comments (Work in progress)
- [ ] save emty lines
- [ ] PrettyPrinter also prints comments and empty lines.
- [ ] Configurable printing rules
- [ ] PrettyPrinter optionally saves non changed nodes as-is

You right `Printer` struct must be renamed to `PrettyPrinter`.

**Comment by z7zmey** [comment]
Now, parser able to save meta(comments and whitespaces) to nodes. The printer prints nodes with meta saved by the parser. At the most cases, the output will be the same as the input (see [printer/printer_parsed_test.go](https://github.com/z7zmey/php-parser/blob/dev/printer/printer_parsed_test.go)).

**Comment by silbinarywolf** [comment]
Nice one! Cheers :)
