### ISSUE TITLE
Parser fails on (valid) string interpolation code

### ISSUE THREAD

**Issue by tylerchr** [z7zmey/php-parser#2]
This is a really interesting project, thanks for working on it. I've run into what looks like an erroneous parse failure with regard to string interpolation code.

```php
<?php
$filename = "something.txt";
@header("Content-Disposition: attachment; filename=\"$filename\"");
```

This fails due to parse errors of various descriptions, depending on what the surrounding code looks like. When using the php-parser binary, this dumps out

```
$ php-parser /tmp/brokenparse.php
==> /private/tmp/brokenparse.php
syntax error: unexpected $end, expecting ')'
  | [*stmt.StmtList]
  |   "Stmts":
```

PHP itself doesn't complain about this code and parses it just fine. Running `php -l /tmp/brokenparse.php` results in no errors. I believe this is related to a flaw in the grammar, because if `$filename` is followed by a space things work fine:

```php
<?php
$filename = "something.txt";
@header("Content-Disposition: attachment; filename=\"$filename \"");
```

```
➜  analyze php-parser /tmp/brokenparse.php
==> /private/tmp/brokenparse.php
  | [*stmt.StmtList]
  |   "Position": Pos{Line: 3-4 Pos: 8-104};
  |   "Stmts":
  |     [*stmt.Expression]

... 52 lines elided ...
```

**Comment by z7zmey** [comment]
Hello @tylerchr.

I have fixed the bug for template strings.
But there is the same bug for backquote and maybe heredoc.

**Comment by tylerchr** [comment]
Wow, thanks for the quick response. That particular issue does seem to be fixed, thank you!

I think there still may be some grammar issues with template strings. 94% of my 2000+ file codebase now parses successfully, and I've mostly narrowed the remaining failures down to these three issues:

**1. Template strings with single-character variable names**

```php
<?php

// causes an apparently infinite loop
"$a=$b{$foo}";

// syntax error: unexpected T_ENCAPSED_AND_WHITESPACE, expecting T_VARIABLE or T_DOLLAR_OPEN_CURLY_BRACES or T_CURLY_OPEN
"foo $b";
```

**2. Variables preceding the `/` character**

The original issue might have been a similar case of this but with the `\` character. This issue seems to exist both inside and outside template strings, and within function calls. I imagine that the same production gets used in all these cases.

```php
<?php

// syntax error: unexpected T_STRING
"$foo/"; 
$foo/100;
($foo/$bar)/5;
"Failed $failed/9 tests";
"http://$foo/bar";
"/foo/$foo/bar/$bar/baz/$baz";

// syntax error: unexpected T_STRING, expecting ')'
ceil($foo/3);
```

For what it's worth, these all parse normally:

```php
<?php

"{$foo}/";
"$foo&bar=$baz";
"$foo ";
"$foo, ";

$foo/ 100;
```

**3. File ends in a comment**

This one isn't as critical and isn't strictly template-string-related, but is the only other grammar failure I've seen.

```php
<?php

"hello";

// File ends in comment // syntax error: unexpected '/'
```

**Comment by z7zmey** [comment]
Hi @tylerchr,  I have fixed that cases and cover them with tests. Also, I fixed backquoted strings that had the same bugs.

**Comment by tylerchr** [comment]
Thanks for your attention and fixes here. This project now parses 100% of our codebase without any parse errors, great work!

I intend to use this to write some custom one-off static analysis tools to help understand a large legacy codebase, and expect your project to be very helpful.
