### ISSUE TITLE
Parser crashes on obscure PHP `list` syntax with missing arguments

### ISSUE THREAD

**Issue by tylerchr** [z7zmey/php-parser#44]
I discovered today that the parser fails with an "index out of range" runtime error when it encounters the following PHP code:

```php
<?php
$things = ["foo", "bar"];
list(, $bar) = $things;
```

Surprisingly, this is valid PHP code (running it results in `bar`).

php-parser gets really unhappy about the lack of a first argument though:

```
panic: runtime error: index out of range
```

I almost feel bad reporting this because it's such bad PHP code, but it's nonetheless valid and should probably at least not crash the parser.

**Comment by z7zmey** [comment]
There was a bug. I tried to save comments to nil element.

Now parser does not trim first nil, which represents the missed item.
Also, it does not trim last nil if array item list ends by a comma.
