### ISSUE TITLE
no parse error when an abstract method contain body

### ISSUE THREAD

**Issue by azjezz** [z7zmey/php-parser#46]
PHP Usually throws a Fatal Error when an abstract method contain a body, even if its not used. but PHP-parser does not. 

example : 

```php
<?php


namespace Foo;

abstract class Bar extends Baz
{
    private $int = 5;
    protected $val = 'value';
    public $bol = false;
    
    abstract function name(): string
    {
    }
    
	public function greet(): void
	{
		echo "Hello World";
	}
}

$main = function (int $argc,string ...$args): void {
    $class = new class extends Bar {
        public function name(): string {
            return 'azjezz';            
        }
    };
    $class->greet();
};

$main($_SERVER['argc'], ...$_SERVER['args']);
```

Expected : 
```
fatal error: Abstract function Foo\Bar::name() cannot contain body in %s on line %d
```
PHP Behavior : 
https://3v4l.org/llHmE

**Comment by z7zmey** [comment]
PHP equally parse `class` and `abstract class` and checks methods at the compile step.

See [zend_language_parser.y:504-519](https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y#L504) and [zend_compile.c:5780](https://github.com/php/php-src/blob/master/Zend/zend_compile.c#L5780)

There are many such checks, so I created another issue #47
