### ISSUE TITLE
Feature request: Changing the logo

### ISSUE THREAD

**Issue by vikramdurai** [z7zmey/php-parser#5]
Can you change the logo for this project? It looks like the gopher ate the elephant. I would recommend changing it to a gopher *playing* with an elephant.

**Comment by z7zmey** [comment]
What about this variant? Gopher in the shirt with the PHP logo.

![photo_2018-04-06_17-55-14](https://user-images.githubusercontent.com/3993597/38428142-b7576ca2-39c3-11e8-9c79-929c8363a2f3.jpg)

**Comment by vikramdurai** [comment]
Better!
I still think that showing the elephant playing with the gopher is better, because it symbolizes that this we are PHP at heart but we have Go in mind :)
