### ISSUE TITLE
print echo

### ISSUE THREAD

**Issue by blue-bird1** [z7zmey/php-parser#78]
php-parse print `echo` node will use short-tags. but if php not allow `short_open_tag`,this will is a error.I don't think the project has any reason to use this.

**Comment by blue-bird1** [comment]
Since PHP 5.4.0,<?= is always available. But I still think that this is not necessary, the printer does not need to do this kind of thing.

**Comment by z7zmey** [comment]
Thanks, you right, by default printer must write `<?php echo ... ?>` instead of `<?= ... ?>`
