### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by z7zmey** [z7zmey/php-parser#82]

**Comment by ruudk** [comment]
Any news on this? 🙏

**Comment by z7zmey** [comment]
I worked on #81, but admit defeat. 
I have not dealt with this task yet, but this task is the main priority.

**Comment by z7zmey** [comment]
```PHP
$str = <<<FOO
abcdefg
    FOO
FOO;
```
There is a backward incompatibility in the scanner. The example above invalid since PHP 7.3. So parser will have to know the minor version to parse a code correctly.

**Comment by ruudk** [comment]
Maybe by default it could use the new syntax and option to specify the old one?

**Comment by z7zmey** [comment]
Agree, by default it would be the latest version.

**Comment by z7zmey** [comment]
Also, I plan not to handle heredoc indentation. Only allow whitespace before the end label and other tokens before the new line.

If somebody wants to strip indentations, it will be able to check and handle the string manually in the client code.
