### ISSUE TITLE
Error while parsing single quoted string with NUL (\0).

### ISSUE THREAD

**Issue by ganlvtech** [z7zmey/php-parser#89]
```php
<?php
$a = ' ';
var_dump($a);
```

The space above between quotes is a `0x00` byte. You can download the attachment [test.zip](https://github.com/z7zmey/php-parser/files/3239135/test.zip).

Related links:

* https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.single

**Comment by z7zmey** [comment]
This issue already fixed in new lexer #80
