### ISSUE TITLE
Empty array elements and trailing comma in array literals

### ISSUE THREAD

**Issue by quasilyte** [z7zmey/php-parser#90]
At some point, php parser started to parse `[1, 2,]` as array of 3 elements where the last array element consisting of key=nil and val=nil.

If we dig further, it also parses something like `[,,,]` as an array of 4 (empty) elements.

Is it intended behavior?

**Comment by quasilyte** [comment]
Relevant comment: https://github.com/VKCOM/noverify/pull/108#issuecomment-497758847
Seems like it's not an issue.

**Comment by z7zmey** [comment]
As @YuriyNasretdinov mentioned, it is a way to represent skipped elements in a `list`. 
Unfortunately `array` and `list` use the same syntax rules to parse their items, so PHP engine checks empty elements at the compile phase https://github.com/php/php-src/blob/775e86344f05f3332463003230ef93df8167ab6c/Zend/zend_compile.c#L7666

**Comment by quasilyte** [comment]
Thanks. That resolves my question.
